# -*- coding: utf-8 -*-
"""local_lorentz_covarience.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vryvqtCTRc_4VqZpvn9Jm3OrsGdRCmwL
"""

import sympy as sp

# Symbols


t, r = sp.symbols("t r", positive=True, real=True)

a = sp.Function("a")(t)
W = sp.Function("W")(t, r)

adot = sp.diff(a, t)
Wdot = sp.diff(W, t)
Wr = sp.diff(W, r)

# spatial indices: i,j = 1,2,3
indices = [1, 2, 3]

# abstract radial unit vector components
n = {
    1: sp.Symbol("n1", real=True),
    2: sp.Symbol("n2", real=True),
    3: sp.Symbol("n3", real=True),
}

def delta(i, j):
    return 1 if i == j else 0


def p(title):
    print("\n" + "=" * 70)
    print(title)
    print("=" * 70)

def simp(x):
    return sp.simplify(x)


p("TETRAD")

print("e^0 = dt")
for i in indices:
    print(f"e^{i} = a dx^{i} + W n{i} dt")

p("DERIVATIVE OF n_i")

dn = {}

for i in indices:
    for j in indices:
        dn[(i, j)] = simp((delta(i, j) - n[i] * n[j]) / r)
        print(f"∂_{j} n_{i} = {dn[(i,j)]}")


p("DERIVATIVE OF W n_i")

dWn_dt = {}
dWn_dx = {}

for i in indices:
    dWn_dt[i] = simp(Wdot * n[i])
    print(f"∂_t(W n_{i}) = {dWn_dt[i]}")

print()

for i in indices:
    for j in indices:
        dWn_dx[(i, j)] = simp(Wr * n[i] * n[j] + W * dn[(i, j)])
        print(f"∂_{j}(W n_{i}) = {dWn_dx[(i,j)]}")


p("INITIAL TORSION")

print("T^0 = 0")

T = {}

for i in indices:
    T[i] = {}
    for j in indices:
        T[i][j] = simp(adot * delta(i, j) - dWn_dx[(i, j)])

print()

for i in indices:
    print(f"T^{i} =")
    for j in indices:
        print(f"  coefficient of dt∧dx^{j}: {T[i][j]}")
    print()

p("EIGENVALUES")

T_parallel = simp(adot - Wr)
T_perp = simp(adot - W / r)

print("T_parallel =", T_parallel)
print("T_perp     =", T_perp)


p("LORENTZ BOOST PARAMETER")

beta = {}

for i in indices:
    beta[i] = simp(-W * n[i])
    print(f"beta_{i} = {beta[i]}")

p("BOOSTED TETRAD")

print("e'^i = e^i + beta_i e^0")
for i in indices:
    print(f"e'^{i} = a dx^{i}")

print()
print("e'^0 = e^0 + beta_i e^i")
print("e'^0 = dt - a W n_i dx^i")
print("e'^0 = dt - a W dr")

p("GENERATED SPIN CONNECTION")

omega_i0_dt = {}
omega_i0_dx = {}

for i in indices:
    omega_i0_dt[i] = dWn_dt[i]

    print(f"omega'^{i}_0 =")
    print(f"  dt component:")
    print(f"    {omega_i0_dt[i]} dt")

    print(f"  spatial components:")
    for j in indices:
        omega_i0_dx[(i, j)] = dWn_dx[(i, j)]
        print(f"    {omega_i0_dx[(i,j)]} dx^{j}")
    print()

print("Using the same convention as the LaTeX calculation:")
print("omega'^0_i = d(W n_i)")


p("TRANSFORMED SPATIAL TORSION")

Tp = {}

for i in indices:
    Tp[i] = {}
    for j in indices:
        Tp[i][j] = simp(adot * delta(i, j) - dWn_dx[(i, j)])

for i in indices:
    print(f"T'^{i} =")
    for j in indices:
        print(f"  coefficient of dt∧dx^{j}: {Tp[i][j]}")
    print()


p("CHECK SPATIAL TORSION")

for i in indices:
    ok = True

    for j in indices:
        diff = simp(Tp[i][j] - T[i][j])

        if diff != 0:
            ok = False

    print(f"T'^{i} = T^{i} ?  {ok}")

p("TRANSFORMED TEMPORAL TORSION")

T0 = {j: 0 for j in indices}
Tp0 = {}

for j in indices:
    Tp0[j] = simp(-adot * W * n[j])

print("T^0 = 0")
print()

print("T'^0 =")
for j in indices:
    print(f"  coefficient of dt∧dx^{j}: {Tp0[j]}")

print()
print("Compact form:")
print("T'^0 = - adot W dt∧dr")


p("CHECK TEMPORAL TORSION")

temporal_equal = True

for j in indices:
    diff = simp(Tp0[j] - T0[j])

    if diff != 0:
        temporal_equal = False

print(f"T'^0 = T^0 ?   {temporal_equal}")
print(f"T'^0 != T^0 ?  {not temporal_equal}")



p("FINAL RESULT")

print("Spatial torsion:")
print("T'^i = T^i  -> TRUE")

print()
print("Temporal torsion:")
print("T'^0 != T^0 -> TRUE")

print()
print("Therefore the radial W shift is not removed as a pure gauge mode.")
print("The transformed temporal torsion is nonzero:")
print("T'^0 = - adot W dt∧dr")