# -*- coding: utf-8 -*-
"""torsion_invarients.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DmIEWyc9C8k67M04QWUpFrixexGEGqv4
"""

import sympy as sp

#symbols
Kpar, Kperp, beta = sp.symbols("Kpar Kperp beta", real=True)
H, a, W, Wr, r = sp.symbols("H a W Wr r", real=True)

gamma = 1 / sp.sqrt(1 - beta**2)

dim = 4
eta = sp.diag(-1, 1, 1, 1)

subs_general = {
    Kpar: H - Wr/a,
    Kperp: H - W/(a*r)
}

subs_static = {
    H: 0,
    a: 1
}

#tensor functions
def zero_tensor():
    return sp.MutableDenseNDimArray.zeros(dim, dim, dim)

def simplify_value(value):
    if isinstance(value, list):
        return [sp.simplify(v) for v in value]
    return sp.simplify(value)

def substitute_value(value, subs):
    if isinstance(value, list):
        return [sp.simplify(v.subs(subs)) for v in value]
    return sp.simplify(value.subs(subs))


# Initial torsion tensor T^a_{bc}


def build_initial_torsion():
    T = zero_tensor()

    # 0 = time
    # 1 = radial
    # 2,3 = transverse angular directions

    eigenvalues = {
        1: Kpar,
        2: Kperp,
        3: Kperp
    }

    for i, Ki in eigenvalues.items():
        T[i, 0, i] = Ki
        T[i, i, 0] = -Ki

    return T


# Lorentz boost in radial direction


def radial_boost_matrix():
    return sp.Matrix([
        [gamma, -gamma*beta, 0, 0],
        [-gamma*beta, gamma, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ])

def transform_torsion_covariantly(T):
    """
    Spin connection included case.

    T'^a_{bc}
    =
    Lambda^a_d
    (Lambda^{-1})^e_b
    (Lambda^{-1})^f_c
    T^d_{ef}
    """
    Lam = radial_boost_matrix()
    Lam_inv = Lam.inv()

    Tp = zero_tensor()

    for A in range(dim):
        for B in range(dim):
            for C in range(dim):
                expr = 0
                for D in range(dim):
                    for E in range(dim):
                        for F in range(dim):
                            expr += (
                                Lam[A, D]
                                * Lam_inv[E, B]
                                * Lam_inv[F, C]
                                * T[D, E, F]
                            )
                Tp[A, B, C] = sp.simplify(expr)

    return Tp


def lower_first_index(Tup):
    Tlow = zero_tensor()

    for A in range(dim):
        for B in range(dim):
            for C in range(dim):
                Tlow[A, B, C] = sp.simplify(
                    sum(eta[A, D] * Tup[D, B, C] for D in range(dim))
                )

    return Tlow

def raise_all_indices(Tlow):
    Tallup = zero_tensor()

    for A in range(dim):
        for B in range(dim):
            for C in range(dim):
                Tallup[A, B, C] = sp.simplify(
                    sum(
                        eta[A, D] * eta[B, E] * eta[C, F] * Tlow[D, E, F]
                        for D in range(dim)
                        for E in range(dim)
                        for F in range(dim)
                    )
                )

    return Tallup

def torsion_vector(Tup):
    """
    T_a = T^b_{b a}
    """
    return [
        sp.simplify(sum(Tup[B, B, A] for B in range(dim)))
        for A in range(dim)
    ]

def vector_square(V):
    """
    V_a V^a = eta^{ab} V_a V_b
    """
    return sp.simplify(
        sum(eta[A, B] * V[A] * V[B] for A in range(dim) for B in range(dim))
    )

def axial_vector(Tup):
    """
    A^a = 1/6 epsilon^{abcd} T_bcd
    """
    Tlow = lower_first_index(Tup)

    A_vec = []
    for A in range(dim):
        expr = 0
        for B in range(dim):
            for C in range(dim):
                for D in range(dim):
                    expr += sp.LeviCivita(A, B, C, D) * Tlow[B, C, D]
        A_vec.append(sp.simplify(expr / 6))

    return A_vec

def invariant_I1(Tup):
    """
    I1 = T_abc T^abc
    """
    Tlow = lower_first_index(Tup)
    Tallup = raise_all_indices(Tlow)

    return sp.simplify(
        sum(
            Tlow[A, B, C] * Tallup[A, B, C]
            for A in range(dim)
            for B in range(dim)
            for C in range(dim)
        )
    )

def invariant_I2(Tup):
    """
    I2 = T_abc T^cba
    """
    Tlow = lower_first_index(Tup)
    Tallup = raise_all_indices(Tlow)

    return sp.simplify(
        sum(
            Tlow[A, B, C] * Tallup[C, B, A]
            for A in range(dim)
            for B in range(dim)
            for C in range(dim)
        )
    )

def tegr_torsion_scalar(Tup):
    """
    T = 1/4 I1 + 1/2 I2 - T_a T^a
    """
    V = torsion_vector(Tup)

    return sp.simplify(
        sp.Rational(1, 4) * invariant_I1(Tup)
        + sp.Rational(1, 2) * invariant_I2(Tup)
        - vector_square(V)
    )

def all_invariants(Tup):
    V = torsion_vector(Tup)
    A = axial_vector(Tup)

    return {
        "Torsion vector T_a": V,
        "Axial vector A^a": A,
        "I1 = T_abc T^abc": invariant_I1(Tup),
        "I2 = T_abc T^cba": invariant_I2(Tup),
        "T_a T^a": vector_square(V),
        "A_a A^a": vector_square(A),
        "TEGR torsion scalar T": tegr_torsion_scalar(Tup),
    }


def print_block(title, data):
    print("\n" + "=" * len(title))
    print(title)
    print("=" * len(title))

    for key, value in data.items():
        print(f"{key} = {simplify_value(value)}")

def print_substituted_block(title, data, subs):
    print("\n" + "=" * len(title))
    print(title)
    print("=" * len(title))

    for key, value in data.items():
        print(f"{key} = {substitute_value(value, subs)}")

def print_differences(title, data1, data2):
    print("\n" + "=" * len(title))
    print(title)
    print("=" * len(title))

    keys = [
        "I1 = T_abc T^abc",
        "I2 = T_abc T^cba",
        "T_a T^a",
        "A_a A^a",
        "TEGR torsion scalar T",
    ]

    for key in keys:
        print(f"{key}: {sp.simplify(data2[key] - data1[key])}")


T_initial = build_initial_torsion()
T_boosted = transform_torsion_covariantly(T_initial)

initial = all_invariants(T_initial)
boosted = all_invariants(T_boosted)

print_block("Boost öncesi invariantlar: Kpar, Kperp formu", initial)

print_substituted_block(
    "Boost öncesi invariantlar: H, a, W, Wr, r formu",
    initial,
    subs_general
)

print_substituted_block(
    "Boost öncesi invariantlar: statik limit a=1, H=0",
    initial,
    {**subs_general, **subs_static}
)

print_block(
    "Boost sonrası invariantlar: spin connection dahil, Kpar, Kperp formu",
    boosted
)

print_differences(
    "Boost sonrası - boost öncesi farklar",
    initial,
    boosted
)