# -*- coding: utf-8 -*-
"""torsion_scalar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HmSyCAG_A5GlQfgUI07Nn5VvZWoFqVlu
"""

import sympy as sp

sp.init_printing()

# Coordinates
t, x, y, z = sp.symbols('t x y z')

# Scale factor
a = sp.Function('a')(t)
H = sp.diff(a, t)/a

# Small expansion parameter
eps = sp.symbols('eps')

# Generic shift vector
W1 = eps * sp.Function('W1')(t, x, y, z)
W2 = eps * sp.Function('W2')(t, x, y, z)
W3 = eps * sp.Function('W3')(t, x, y, z)

coords = [x, y, z]
W = [W1, W2, W3]

# A_ij = H delta_ij - (1/a) d_j W_i
A = sp.Matrix(3, 3, lambda i, j:
    H * sp.KroneckerDelta(i, j)
    - sp.diff(W[i], coords[j]) / a
)

print("\nA_ij =")
sp.pprint(A)

# Trace(A)
TrA = sp.simplify(A.trace())

print("\nTrace(A) =")
sp.pprint(TrA)

# TEGR torsion scalar
term1 = TrA**2

term2 = sp.Rational(1,2) * sum(
    A[i,j] * A[i,j]
    for i in range(3)
    for j in range(3)
)

term3 = sp.Rational(1,2) * sum(
    A[i,j] * A[j,i]
    for i in range(3)
    for j in range(3)
)

Tscalar = sp.expand(term1 - term2 - term3)

print("\nFull torsion scalar T =")
sp.pprint(Tscalar)

# Linear order in eps
Tlinear = sp.series(Tscalar, eps, 0, 2).removeO()
Tlinear = sp.expand(Tlinear)

print("\nLinearized torsion scalar:")
sp.pprint(Tlinear)

# Expected analytic form
divW = (
    sp.diff(W1/eps, x)
    + sp.diff(W2/eps, y)
    + sp.diff(W3/eps, z)
)

Texpected = 6*H**2 - (4*H/a)*divW

print("\nExpected analytic expression:")
sp.pprint(sp.expand(Texpected))

print("\nDifference:")
sp.pprint(sp.simplify(Tlinear.subs(eps,1) - Texpected))

# ============================================================
# Radial case
# ============================================================

r = sp.sqrt(x**2 + y**2 + z**2)

Wr = sp.Function('W')(t, r)

Wr1 = Wr * x/r
Wr2 = Wr * y/r
Wr3 = Wr * z/r

divWr = (
    sp.diff(Wr1, x)
    + sp.diff(Wr2, y)
    + sp.diff(Wr3, z)
)

divWr = sp.simplify(divWr)

print("\nRadial divergence ∂_i W_i =")
sp.pprint(divWr)

# Radial torsion scalar
Tradial = sp.expand(
    6*H**2 - (4*H/a)*divWr
)

print("\nRadial torsion scalar:")
sp.pprint(Tradial)